# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hourglass.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QCheckBox


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 400)
        MainWindow.setMinimumSize(QtCore.QSize(900, 400))
        MainWindow.setMaximumSize(QtCore.QSize(900, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        MainWindow.setPalette(palette)
        # font = QtGui.QFont()
        # # font.setFamily("Aerial")
        # MainWindow.setFont(font)
        MainWindow.setStyleSheet("/* REMOVE THIS BG LINE BELOW WHEN READY TO GO TO PROD */\n"
                                 "\n"
                                 "/* background-image: url(:/bg/bg.png);\n"
                                 "*/\n"
                                 "\n"
                                 "QMainWindow {\n"
                                 "    background-image: url(:/bg/bg.png);\n"
                                 "    /*setWindowFlags(Qt::FramelessWindowHint);  */\n"
                                 "}\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLineEdit {\n"
                                         "    border-radius: 10px;  /* Adjust the value for more/less rounding */\n"
                                         "    border: 2px solid #cccccc;  /* Optional: a border color */\n"
                                         "    border-color: black;\n"
                                         "    padding: 5px;  /* Optional: padding inside the text area */\n"
                                         "    background-color: #23192f;\n"
                                         "    color:#1fe3b1 ;\n"
                                         "    text-align: center;\n"
                                         "}\n"
                                         "\n"
                                         "QComboBox {\n"
                                         "    border-radius: 8px;  /* Adjust value for more/less rounding */\n"
                                         "    border: 2px solid #cccccc;  /* Border color */\n"
                                         "    border-color: black;\n"
                                         "    padding: 5px;  /* Padding inside the box */\n"
                                         "    background-color: #23192f;  /* Background color */\n"
                                         "    color: #1fe3b1;  /* Text color */\n"
                                         "    text-align: center;  /* Center-aligns text */\n"
                                         "}\n"
                                         "\n"
                                         "QComboBox::drop-down {\n"
                                         "    border-left: 2px solid #1fe3b1;  /* Border color for drop-down arrow container */\n"
                                         "    border-radius:2px;\n"
                                         "    background-color: #23192f;  /* Ensure background color of the drop-down is set */\n"
                                         "}\n"
                                         "\n"
                                         "QComboBox::down-arrow {\n"
                                         "    width: 10px;  /* Adjust width */\n"
                                         "    height: 10px;  /* Adjust height */\n"
                                         "}\n"
                                         "\n"
                                         "QComboBox QAbstractItemView {\n"
                                         "    background-color: #23192f;  /* Background color of the drop-down list */\n"
                                         "    selection-background-color: #1fe3b1;  /* Background color of selected item */\n"
                                         "    selection-color: #23192f;  /* Text color of selected item */\n"
                                         "    color: #1fe3b1;  /* Text color of unselected items */\n"
                                         "}\n"
                                         "\n"
                                         "QComboBox::item {\n"
                                         "    background-color: #23192f;  /* Background color of the items */\n"
                                         "    color: #1fe3b1;  /* Text color of the items */\n"
                                         "}\n"
                                         "\n"
                                         "QComboBox::item:selected {\n"
                                         "    background-color: #1fe3b1;  /* Background color of the selected item */\n"
                                         "    color: #23192f;  /* Text color of the selected item */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton {\n"
                                         "    background-color: #23192f;  /* Background color */\n"
                                         "    color: #1fe3b1;  /* Text color */\n"
                                         "    border: 2px solid #1fe3b1;  /* Border color */\n"
                                         "    border-radius: 8px;  /* Rounded corners */\n"
                                         "    padding: 10px 20px;  /* Padding inside the button */\n"
                                         "    font-family: \'Aerial\';  /* Font family */\n"
                                         "    font-size: 12pt;  /* Font size */\n"
                                         "    font-weight: bold;  /* Font weight */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #1fe3b1;  /* Background color on hover */\n"
                                         "    color: #fff;  /* Text color on hover */\n"
                                         "    border: 2px solid #fff;  /* Border color on hover */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "    background-color: #1fe3b1;  /* Background color when pressed */\n"
                                         "    color: #23192f;  /* Text color when pressed */\n"
                                         "    border: 2px solid #1fe3b1;  /* Border color when pressed */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:disabled {\n"
                                         "    background-color: #444;  /* Background color when disabled */\n"
                                         "    color: #888;  /* Text color when disabled */\n"
                                         "    border: 2px solid #888;  /* Border color when disabled */\n"
                                         "}\n"
                                         "\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_C_LVL = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_C_LVL.setEnabled(True)
        self.textEdit_C_LVL.setGeometry(QtCore.QRect(190, 70, 111, 31))
        font = QtGui.QFont()
        # # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_C_LVL.setFont(font)
        self.textEdit_C_LVL.setStyleSheet("")
        self.textEdit_C_LVL.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhPreferNumbers)
        # self.textEdit_C_LVL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.textEdit_C_LVL.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_C_LVL.setPlaceholderText("")
        self.textEdit_C_LVL.setObjectName("textEdit_C_LVL")
        self.label_C_LVL = QtWidgets.QLabel(self.centralwidget)
        self.label_C_LVL.setGeometry(QtCore.QRect(10, 70, 161, 31))
        font = QtGui.QFont()
        # # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_C_LVL.setFont(font)
        self.label_C_LVL.setStyleSheet("QLabel {\n"
                                       "    background-color: none;  /* Make the background transparent */\n"
                                       "    color: #1fe3b1;  /* Set the text color */\n"
                                       "    border: 0px;  /* Remove any border */\n"
                                       "    padding: 0px;  /* Remove any padding */\n"
                                       "}")
        self.label_C_LVL.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_C_LVL.setLineWidth(0)
        self.label_C_LVL.setObjectName("label_C_LVL")
        self.label_T_LVL = QtWidgets.QLabel(self.centralwidget)
        self.label_T_LVL.setGeometry(QtCore.QRect(10, 120, 161, 31))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_T_LVL.setFont(font)
        self.label_T_LVL.setStyleSheet("QLabel {\n"
                                       "    background-color: none;  /* Make the background transparent */\n"
                                       "    color: #1fe3b1;  /* Set the text color */\n"
                                       "    border: 0px;  /* Remove any border */\n"
                                       "    padding: 0px;  /* Remove any padding */\n"
                                       "}")
        self.label_T_LVL.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_T_LVL.setLineWidth(0)
        self.label_T_LVL.setObjectName("label_T_LVL")
        self.textEdit_T_LVL = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_T_LVL.setEnabled(True)
        self.textEdit_T_LVL.setGeometry(QtCore.QRect(190, 120, 111, 31))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_T_LVL.setFont(font)
        self.textEdit_T_LVL.setStyleSheet("")
        self.textEdit_T_LVL.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhPreferNumbers)
        # self.textEdit_T_LVL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.textEdit_T_LVL.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_T_LVL.setPlaceholderText("")
        self.textEdit_T_LVL.setObjectName("textEdit_T_LVL")
        self.label_WINRATE = QtWidgets.QLabel(self.centralwidget)
        self.label_WINRATE.setGeometry(QtCore.QRect(10, 170, 161, 31))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_WINRATE.setFont(font)
        self.label_WINRATE.setStyleSheet("QLabel {\n"
                                         "    background-color: none;  /* Make the background transparent */\n"
                                         "    color: #1fe3b1;  /* Set the text color */\n"
                                         "    border: 0px;  /* Remove any border */\n"
                                         "    padding: 0px;  /* Remove any padding */\n"
                                         "}")
        self.label_WINRATE.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_WINRATE.setLineWidth(0)
        self.label_WINRATE.setObjectName("label_WINRATE")
        self.label_EXPB = QtWidgets.QLabel(self.centralwidget)
        self.label_EXPB.setGeometry(QtCore.QRect(10, 220, 161, 31))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_EXPB.setFont(font)
        self.label_EXPB.setStyleSheet("QLabel {\n"
                                      "    background-color: none;  /* Make the background transparent */\n"
                                      "    color: #1fe3b1;  /* Set the text color */\n"
                                      "    border: 0px;  /* Remove any border */\n"
                                      "    padding: 0px;  /* Remove any padding */\n"
                                      "}")
        self.label_EXPB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_EXPB.setLineWidth(0)
        self.label_EXPB.setObjectName("label_EXPB")
        self.textEdit_WINRATE = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_WINRATE.setEnabled(True)
        self.textEdit_WINRATE.setGeometry(QtCore.QRect(190, 170, 111, 31))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_WINRATE.setFont(font)
        self.textEdit_WINRATE.setStyleSheet("")
        self.textEdit_WINRATE.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhPreferNumbers)
        # self.textEdit_WINRATE.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.textEdit_WINRATE.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_WINRATE.setPlaceholderText("")
        self.textEdit_WINRATE.setObjectName("textEdit_WINRATE")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 220, 111, 31))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(8)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_CALC = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CALC.setGeometry(QtCore.QRect(120, 300, 131, 41))  # Original placement: 120, 280, 131, 41
        self.checkbox = QtWidgets.QCheckBox("Loss Farm", self.centralwidget)
        self.checkbox.setGeometry(QtCore.QRect(50, 260, 150, 30))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_CALC.setFont(font)
        self.pushButton_CALC.setObjectName("pushButton_CALC")
        self.label_TITLE = QtWidgets.QLabel(self.centralwidget)
        self.label_TITLE.setGeometry(QtCore.QRect(290, 10, 331, 31))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_TITLE.setFont(font)
        self.label_TITLE.setStyleSheet("QLabel {\n"
                                       "    background-color: none;  /* Make the background transparent */\n"
                                       "    color: #1fe3b1;  /* Set the text color */\n"
                                       "    border: 0px;  /* Remove any border */\n"
                                       "    padding: 0px;  /* Remove any padding */\n"
                                       "    font-size: 24;\n"
                                       "}")
        self.label_TITLE.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_TITLE.setLineWidth(0)
        self.label_TITLE.setObjectName("label_TITLE")
        self.title_line = QtWidgets.QFrame(self.centralwidget)
        self.title_line.setGeometry(QtCore.QRect(310, 40, 301, 20))
        self.title_line.setStyleSheet("border:0;\n"
                                      "border-top: 3px solid #1fe3b1;\n"
                                      "")
        self.title_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.title_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.title_line.setObjectName("title_line")
        self.title_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.title_line_2.setGeometry(QtCore.QRect(530, 70, 361, 20))
        self.title_line_2.setStyleSheet("border:0;\n"
                                        "border-top: 3px solid #1fe3b1;\n"
                                        "")
        self.title_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.title_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.title_line_2.setObjectName("title_line_2")
        self.title_line_3 = QtWidgets.QFrame(self.centralwidget)
        self.title_line_3.setGeometry(QtCore.QRect(530, 320, 361, 16))
        self.title_line_3.setStyleSheet("border:0;\n"
                                        "border-top: 3px solid #1fe3b1;\n"
                                        "")
        self.title_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.title_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.title_line_3.setObjectName("title_line_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(530, 70, 16, 251))
        self.line.setStyleSheet("    border: 0;\n"
                                "    border-left: 3px solid #1fe3b1;  /* Vertical line */\n"
                                "    height: 100px;  /* Set height */\n"
                                "    width: 0;  /* Set width to 0 */")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(890, 70, 20, 251))
        self.line_2.setStyleSheet("    border: 0;\n"
                                  "    border-left: 3px solid #1fe3b1;  /* Vertical line */\n"
                                  "    height: 100px;  /* Set height */\n"
                                  "    width: 0;  /* Set width to 0 */")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 70, 361, 251))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("    color: #1fe3b1;\n"
                                 "    padding: 2px;")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton_SAVE = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SAVE.setGeometry(QtCore.QRect(660, 330, 111, 41))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SAVE.setFont(font)
        self.pushButton_SAVE.setObjectName("pushButton_SAVE")
        self.textEdit_C_LVL.raise_()
        self.label_C_LVL.raise_()
        self.label_T_LVL.raise_()
        self.textEdit_T_LVL.raise_()
        self.label_WINRATE.raise_()
        self.label_EXPB.raise_()
        self.textEdit_WINRATE.raise_()
        self.comboBox.raise_()
        self.pushButton_CALC.raise_()
        self.checkbox.raise_()
        self.label_TITLE.raise_()
        self.title_line_2.raise_()
        self.title_line_3.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.title_line.raise_()
        self.label.raise_()
        self.pushButton_SAVE.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        self.menuBar.setFont(font)
        self.menuBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuBar.setAutoFillBackground(False)
        self.menuBar.setStyleSheet("\n"
                                   "QMenuBar {\n"
                                   "    background-color: transparent; \n"
                                   "    color: #FE0101;            \n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "QMenuBar::item {\n"
                                   "    background-color: transparent;  /* Slightly lighter background color for menu items */\n"
                                   "    color: #1fe3b1;             /* White text color for menu items */\n"
                                   "}\n"
                                   "\n"
                                   "QMenuBar::item:selected {\n"
                                   "    background-color: #1fe3b1;  /* Background color when an item is hovered over */\n"
                                   "    color: #23192f;             /* White text color for the selected item */\n"
                                   "}\n"
                                   "\n"
                                   "QMenuBar::item:disabled {\n"
                                   "    color: #fff;             /* Lighter color for disabled menu items */\n"
                                   "}\n"
                                   "\n"
                                   "/* Styles for QMenu (dropdowns) */\n"
                                   "QMenu {\n"
                                   "    background-color: transparent;  /* Background color of the dropdown menu */\n"
                                   "    border: 1px solid #444;  /* Border around the dropdown menu */\n"
                                   "}\n"
                                   "\n"
                                   "QMenu::item {\n"
                                   "    background-color: transparent;  /* Transparent background for menu items in dropdowns */\n"
                                   "    color: #1fe3b1;                 /* Text color for menu items in dropdowns */\n"
                                   "}\n"
                                   "\n"
                                   "QMenu::item:selected {\n"
                                   "    background-color: #1fe3b1;  /* Background color when an item is hovered over in dropdown */\n"
                                   "    color:  #23192f;             /* Text color of the selected item in dropdown */\n"
                                   "}\n"
                                   "\n"
                                   "QMenu::item:disabled {\n"
                                   "    color: #888;             /* Lighter color for disabled items in dropdown */\n"
                                   "}\n"
                                   "\n"
                                   "QMenu::separator {\n"
                                   "    height: 2px;                /* Height of the separator line */\n"
                                   "    background-color: #23192f;    /* Color of the separator line */\n"
                                   "    margin: 5px 0;             /* Space above and below the separator */\n"
                                   "}")
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        font.setBold(False)
        font.setWeight(50)
        self.menuHelp.setFont(font)
        self.menuHelp.setAutoFillBackground(False)
        self.menuHelp.setStyleSheet("")
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionEvents = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        self.actionEvents.setFont(font)
        self.actionEvents.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionEvents.setObjectName("actionEvents")
        self.actionWin_Rate = QtWidgets.QAction(MainWindow)
        self.actionWin_Rate.setCheckable(False)
        self.actionWin_Rate.setObjectName("actionWin_Rate")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setCheckable(False)
        font = QtGui.QFont()
        # font.setFamily("Aerial")
        self.actionUpdate.setFont(font)
        self.actionUpdate.setObjectName("actionUpdate")
        self.menuHelp.addAction(self.actionUpdate)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionEvents)
        self.menuHelp.addAction(self.actionWin_Rate)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        VERSION = "v1.0"
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"Hourglass Calculator"))
        self.label_C_LVL.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Current Level</p></body></html>"))
        self.label_C_LVL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Current Level:</span></p></body></html>"))
        self.label_T_LVL.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Current Level</p></body></html>"))
        self.label_T_LVL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Target Level:</span></p></body></html>"))
        self.label_WINRATE.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Current Level</p></body></html>"))
        self.label_WINRATE.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Win-Rate</span></p></body></html>"))
        self.label_EXPB.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Current Level</p></body></html>"))
        self.label_EXPB.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">EXP Boost</span></p></body></html>"))
        self.comboBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Test</p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Gold & Glory"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Community Day"))
        self.pushButton_CALC.setText(_translate("MainWindow", "Calculate"))
        self.checkbox.setText(_translate("MainWindow", "Loss Farm"))
        self.label_TITLE.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Current Level</p></body></html>"))
        self.label_TITLE.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Hourglass Calculator</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Calculation Results...."))
        self.pushButton_SAVE.setText(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionEvents.setText(_translate("MainWindow", "Events / EXP"))
        self.actionWin_Rate.setText(_translate("MainWindow", "Win Rate"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))


import res_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
